version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - data-mongodb:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
      - ME_CONFIG_MONGODB_SERVER=mongodb
  super_coffee:
      build:
        context: ./
        dockerfile: Dockerfile
      container_name: super_coffee
      hostname: super_coffee
      image: super-coffee
      ports:
        - "8080-8080"
      depends_on:
        - mongodb
      env_file: ./.env
      restart: always
volumes:
  data-mongodb:
    name: data-mongodb
networks:
  default:
    name: mongodb_network